title: Testing the Support-kit
description: Just a mock-up that should be expanded.

# Navigasjonsmeny (Topic 2, 3, 4 lenker direkte til sider du oppretter)
navigation:
  - title: Introduction
    url: /
  - title: Topic 2
    url: /entrypoint/
  - title: Topic 3
    url: /topic3/
  - title: Topic 4
    url: /topic4/
