title: All about the Support-kit
description: Lær alt om identifisering av filformater.

# Navigasjonsmeny (Topic 2, 3, 4 lenker direkte til sider du oppretter)
navigation:
  - title: Introduction
    url: /
  - title: Topic 2
    url: /entrypoint/
  - title: Topic 3
    url: /topic3/
  - title: Topic 4
    url: /topic4/
